# -*- coding: utf-8 -*-
from odoo import api, fields, models


class CrmLeadChatbot(models.Model):
    _inherit = 'crm.lead'

    # ── Chatbot Fields ──────────────────────────────────────────────
    chatbot_session_id = fields.Many2one(
        'perfecthr.chatbot.session',
        string='Chatbot Session',
        ondelete='set null',
    )
    chatbot_qualified = fields.Boolean(
        string='AI Qualified',
        default=False,
        help='Whether the AI chatbot qualified this lead.',
    )
    chatbot_score = fields.Integer(
        string='AI Score',
        default=0,
        help='AI qualification score (0-100).',
    )
    employee_size = fields.Selection([
        ('1-10', '1-10'),
        ('11-50', '11-50'),
        ('51-200', '51-200'),
        ('201-500', '201-500'),
        ('501-1000', '501-1000'),
        ('1000+', '1000+'),
    ], string='Employee Size')

    chat_transcript = fields.Html(
        string='Chat Transcript',
        compute='_compute_chat_transcript',
        store=False,
        sanitize=True,
    )

    is_from_chatbot = fields.Boolean(
        string='From Chatbot',
        default=False,
        help='Whether this lead was generated by the AI chatbot.',
    )

    @api.depends('chatbot_session_id', 'chatbot_session_id.message_ids')
    def _compute_chat_transcript(self):
        for rec in self:
            if rec.chatbot_session_id:
                rec.chat_transcript = (
                    rec.chatbot_session_id._get_chat_transcript_html()
                )
            else:
                rec.chat_transcript = False
